# AWS CodeDeploy appspec.yml file
version: 0.0

# The operating system running on the target compute resource.
# For EC2 instances using Ubuntu, RHEL, or Linux Amazon Machine Images (AMI) use Linux as the value.
os: linux

# A list of files to copy on each deployment.
files:
  # A directory to copy in each application revision, if only a "/" is used for the source, all files in that directory are copied.
  - source: /
    destination: /deploy

hooks: 
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 200
      runas: root

  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 900
      runas: root