version: "3.7"

services:
  server:
    image: 592532275118.dkr.ecr.eu-central-1.amazonaws.com/node-app:${BUILD_SHA}
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - app-variables.env