name: "Simple echo workflow"

on: [push]

jobs:
  echo-1:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo job 1 - step 1"
        run: echo "Echor run 1"

  echo-2:
    runs-on: ubuntu-latest
    needs: echo-1
    steps:
      - name: "Echo job 2 - step 1"
        run: echo "Echor run 2"
